#include "installer.hpp"

#include "../system/system.hpp"

#include <filesystem>
#include <fstream>
#include <random>
#include <sstream>

namespace ircord::installer {

namespace {

constexpr std::uintmax_t kMinimumFreeSpaceBytes = 512ull * 1024ull * 1024ull;

std::string Join(const std::vector<std::string>& values, const std::string& separator) {
    std::ostringstream out;
    for (std::size_t i = 0; i < values.size(); ++i) {
        if (i != 0) {
            out << separator;
        }
        out << values[i];
    }
    return out.str();
}

std::string RandomHex(std::size_t bytes) {
    static constexpr char kHex[] = "0123456789abcdef";
    std::random_device rd;
    std::uniform_int_distribution<int> dist(0, 255);

    std::string output;
    output.reserve(bytes * 2);
    for (std::size_t i = 0; i < bytes; ++i) {
        const auto value = static_cast<unsigned char>(dist(rd));
        output.push_back(kHex[(value >> 4) & 0x0F]);
        output.push_back(kHex[value & 0x0F]);
    }
    return output;
}

std::string BuildServerConfig(const InstallConfig& config,
                              const std::filesystem::path& cert_path,
                              const std::filesystem::path& key_path) {
    std::ostringstream out;
    out << "# IRCord Server Configuration\n";
    out << "# Generated by ircord-installer\n\n";
    out << "[server]\n";
    out << "host = \"" << config.listen_address << "\"\n";
    out << "port = " << config.port_text << "\n";
    out << "log_level = \"info\"\n";
    out << "max_connections = 100\n\n";
    out << "[tls]\n";
    out << "cert_file = \"" << cert_path.string() << "\"\n";
    out << "key_file = \"" << key_path.string() << "\"\n\n";
    out << "[database]\n";
    out << "path = \"" << (std::filesystem::path(config.data_path) / "ircord.db").string() << "\"\n\n";
    out << "[limits]\n";
    out << "max_message_bytes = 65536\n";
    out << "ping_interval_sec = 30\n";
    out << "ping_timeout_sec = 60\n";
    out << "msg_rate_per_sec = 20\n";
    out << "conn_rate_per_min = 10\n";
    out << "commands_per_min = 30\n";
    out << "joins_per_min = 5\n";
    out << "abuse_threshold = 5\n";
    out << "abuse_window_min = 10\n";
    out << "ban_duration_min = 30\n\n";
    out << "[security]\n";
    out << "file_encryption_key = \"" << RandomHex(32) << "\"\n";
    return out.str();
}

std::string BuildSystemdUnit(const InstallConfig& config) {
    const auto install_dir = std::filesystem::path(config.install_path);
    const auto data_dir = std::filesystem::path(config.data_path);

    std::ostringstream out;
    out << "[Unit]\n";
    out << "Description=IRCord Chat Server\n";
    out << "After=network.target\n";
    out << "StartLimitIntervalSec=0\n\n";
    out << "[Service]\n";
    out << "Type=simple\n";
    out << "User=ircord\n";
    out << "Group=ircord\n";
    out << "WorkingDirectory=" << install_dir.string() << "\n";
    out << "ExecStart=" << (install_dir / "ircord-server").string()
        << " --headless --config " << (install_dir / "server.toml").string() << "\n";
    out << "Restart=on-failure\n";
    out << "RestartSec=5\n";
    out << "StandardOutput=journal\n";
    out << "StandardError=journal\n";
    out << "SyslogIdentifier=ircord-server\n";
    out << "NoNewPrivileges=yes\n";
    out << "ProtectSystem=strict\n";
    out << "ReadWritePaths=" << data_dir.string() << "\n";
    out << "ReadOnlyPaths=/etc/letsencrypt /etc/ircord\n";
    out << "PrivateTmp=yes\n\n";
    out << "[Install]\n";
    out << "WantedBy=multi-user.target\n";
    return out.str();
}

bool RunOrCapture(const std::string& command,
                  const std::string& error_prefix,
                  const InstallerRunner::ProgressCallback& callback,
                  std::string* error_out) {
    const auto result = SystemOps::RunShell(command);
    if (result.exit_code == 0) {
        return true;
    }

    if (error_out != nullptr) {
        *error_out = error_prefix + "\n" + result.output;
    }
    callback(error_prefix, true);
    return false;
}

}  // namespace

InstallerRunner::InstallerRunner(SystemInfo system_info, Manifest manifest)
    : system_info_(std::move(system_info)), manifest_(std::move(manifest)) {}

std::vector<PreflightIssue> InstallerRunner::RunPreflight(const InstallConfig& config) const {
    std::vector<PreflightIssue> issues;

    if (!system_info_.is_linux) {
        issues.push_back({true, "Linux is required for this installer prototype."});
    }
    if (system_info_.platform_key != "linux-x64" && system_info_.platform_key != "linux-arm64") {
        issues.push_back({true, "Unsupported architecture: " + system_info_.platform_key});
    }
    if (!system_info_.is_root) {
        issues.push_back({true, "Run the installer as root. The bootstrap script can elevate with sudo."});
    }
    if (!system_info_.has_systemd) {
        issues.push_back({true, "systemd was not detected. IRCord service install requires systemd in v1."});
    }
    if (!system_info_.has_apt) {
        issues.push_back({true, "apt-get was not found. Only Debian/Ubuntu style systems are supported in v1."});
    }
    if (!system_info_.distro_id.empty() &&
        system_info_.distro_id != "ubuntu" &&
        system_info_.distro_id != "debian") {
        issues.push_back({true, "Unsupported distribution: " + system_info_.distro_id});
    }
    if (manifest_.server.url.empty()) {
        issues.push_back({true, "Manifest does not contain a server artifact for this platform."});
    }

    const auto parsed_port = SystemOps::ParsePort(config.port_text);
    if (!parsed_port.has_value()) {
        issues.push_back({true, "Port must be a number between 1 and 65535."});
    }
    if (config.domain.empty()) {
        issues.push_back({true, "Domain cannot be empty."});
    }

    std::string path_reason;
    if (!SystemOps::PathWritable(config.install_path, &path_reason)) {
        issues.push_back({true, path_reason});
    }
    if (!SystemOps::PathWritable(config.data_path, &path_reason)) {
        issues.push_back({true, path_reason});
    }

    const auto free_space = SystemOps::FreeSpaceBytes(config.install_path);
    if (free_space < kMinimumFreeSpaceBytes) {
        issues.push_back({true, "Less than 512 MB of free disk space is available in the install path."});
    }

    if (parsed_port.has_value()) {
        std::string port_reason;
        if (!SystemOps::PortAvailable(config.listen_address, *parsed_port, &port_reason)) {
            issues.push_back({true, port_reason});
        }
    }

    if (config.tls_mode == TlsMode::LetsEncrypt) {
        std::string port_80_reason;
        if (!SystemOps::PortAvailable("0.0.0.0", 80, &port_80_reason)) {
            issues.push_back({true, "Port 80 must be free for Let's Encrypt standalone validation."});
        }
    }

    if (config.tls_mode == TlsMode::ExistingCert) {
        if (!std::filesystem::exists(config.existing_cert_path)) {
            issues.push_back({true, "Existing certificate file was not found."});
        }
        if (!std::filesystem::exists(config.existing_key_path)) {
            issues.push_back({true, "Existing key file was not found."});
        }
    }

    if (std::filesystem::exists(std::filesystem::path(config.install_path) / "ircord-server")) {
        issues.push_back({true, "Existing install detected in install_path. Fresh install only in v1."});
    }
    if (std::filesystem::exists("/etc/systemd/system/ircord-server.service")) {
        issues.push_back({true, "Existing ircord-server.service detected. Fresh install only in v1."});
    }

    if (config.manage_firewall && !system_info_.has_ufw && !config.install_ufw_if_missing) {
        issues.push_back({false, "UFW is not installed. Firewall rules will need to be applied manually."});
    }

    return issues;
}

InstallSummary InstallerRunner::RunInstall(const InstallConfig& config,
                                           const ProgressCallback& callback) const {
    InstallSummary summary;
    summary.docs_url = manifest_.docs_url;
    summary.config_path = (std::filesystem::path(config.install_path) / "server.toml").string();

    const auto issues = RunPreflight(config);
    for (const auto& issue : issues) {
        if (issue.blocking) {
            summary.success = false;
            summary.headline = "Preflight failed";
            summary.details.push_back(issue.message);
            return summary;
        }
    }

    const auto parsed_port = SystemOps::ParsePort(config.port_text);
    if (!parsed_port.has_value()) {
        summary.success = false;
        summary.headline = "Invalid port";
        summary.details.push_back("Port must be a number between 1 and 65535.");
        return summary;
    }

    const auto temp_dir = SystemOps::CreateTempDir();
    const auto archive_path = temp_dir / "ircord-server.tar.gz";
    const auto extract_dir = temp_dir / "payload";
    const auto install_dir = std::filesystem::path(config.install_path);
    const auto data_dir = std::filesystem::path(config.data_path);

    std::filesystem::path cert_path;
    std::filesystem::path key_path;
    std::string command_error;

    callback("Installing runtime dependencies", false);
    std::vector<std::string> packages = {"ca-certificates", "curl", "openssl"};
    if (config.tls_mode == TlsMode::LetsEncrypt) {
        packages.push_back("certbot");
    }
    if (config.manage_firewall && !system_info_.has_ufw && config.install_ufw_if_missing) {
        packages.push_back("ufw");
    }
    if (!RunOrCapture("apt-get update -qq", "apt-get update failed", callback, &command_error) ||
        !RunOrCapture("DEBIAN_FRONTEND=noninteractive apt-get install -y -qq " + Join(packages, " "),
                      "Installing runtime packages failed",
                      callback,
                      &command_error)) {
        summary.success = false;
        summary.headline = "Dependency install failed";
        summary.details.push_back(command_error);
        return summary;
    }

    callback("Downloading IRCord server package", false);
    std::string download_error;
    if (!SystemOps::DownloadFile(manifest_.server.url, archive_path, &download_error)) {
        summary.success = false;
        summary.headline = "Server download failed";
        summary.details.push_back(download_error);
        return summary;
    }

    callback("Verifying download integrity", false);
    std::string sha_error;
    if (!SystemOps::VerifySha256(archive_path, manifest_.server.sha256, &sha_error)) {
        summary.success = false;
        summary.headline = "Checksum verification failed";
        summary.details.push_back(sha_error);
        return summary;
    }

    callback("Extracting server payload", false);
    if (!SystemOps::ExtractTarGz(archive_path, extract_dir, &download_error)) {
        summary.success = false;
        summary.headline = "Payload extraction failed";
        summary.details.push_back(download_error);
        return summary;
    }

    const auto server_binary = SystemOps::FindFileRecursive(extract_dir, "ircord-server");
    if (server_binary.empty()) {
        summary.success = false;
        summary.headline = "Payload missing ircord-server";
        summary.details.push_back("The downloaded archive did not contain an ircord-server binary.");
        return summary;
    }

    callback("Creating service user and directories", false);
    std::filesystem::create_directories(install_dir);
    std::filesystem::create_directories(data_dir);
    std::filesystem::create_directories("/etc/ircord");

    if (!RunOrCapture("id -u ircord >/dev/null 2>&1 || useradd -r -s /usr/sbin/nologin -M ircord",
                      "Failed to create ircord service user",
                      callback,
                      &command_error) ||
        !RunOrCapture("chown root:ircord " + SystemOps::ShellEscape(install_dir.string()) +
                          " && chmod 750 " + SystemOps::ShellEscape(install_dir.string()),
                      "Failed to set install directory permissions",
                      callback,
                      &command_error) ||
        !RunOrCapture("chown ircord:ircord " + SystemOps::ShellEscape(data_dir.string()) +
                          " && chmod 750 " + SystemOps::ShellEscape(data_dir.string()),
                      "Failed to set data directory permissions",
                      callback,
                      &command_error)) {
        summary.success = false;
        summary.headline = "Directory setup failed";
        summary.details.push_back(command_error);
        return summary;
    }

    callback("Configuring TLS", false);
    switch (config.tls_mode) {
        case TlsMode::LetsEncrypt:
            cert_path = std::filesystem::path("/etc/letsencrypt/live") / config.domain / "fullchain.pem";
            key_path = std::filesystem::path("/etc/letsencrypt/live") / config.domain / "privkey.pem";
            if (!RunOrCapture(
                    "certbot certonly --standalone --non-interactive --agree-tos "
                    "--register-unsafely-without-email -d " + SystemOps::ShellEscape(config.domain),
                    "Let's Encrypt certificate acquisition failed",
                    callback,
                    &command_error)) {
                summary.success = false;
                summary.headline = "Certificate setup failed";
                summary.details.push_back(command_error);
                return summary;
            }
            break;
        case TlsMode::SelfSigned:
            cert_path = "/etc/ircord/cert.pem";
            key_path = "/etc/ircord/key.pem";
            if (!RunOrCapture(
                    "openssl req -x509 -newkey rsa:4096 -keyout " + SystemOps::ShellEscape(key_path.string()) +
                        " -out " + SystemOps::ShellEscape(cert_path.string()) +
                        " -days 365 -nodes -subj " + SystemOps::ShellEscape("/CN=" + config.domain),
                    "Self-signed certificate generation failed",
                    callback,
                    &command_error) ||
                !RunOrCapture(
                    "chmod 644 " + SystemOps::ShellEscape(cert_path.string()) + " && chmod 600 " +
                        SystemOps::ShellEscape(key_path.string()),
                    "Failed to set certificate permissions",
                    callback,
                    &command_error)) {
                summary.success = false;
                summary.headline = "Certificate setup failed";
                summary.details.push_back(command_error);
                return summary;
            }
            break;
        case TlsMode::ExistingCert:
            cert_path = config.existing_cert_path;
            key_path = config.existing_key_path;
            break;
    }

    callback("Installing server binary", false);
    if (!RunOrCapture(
            "install -o root -g ircord -m 750 " + SystemOps::ShellEscape(server_binary.string()) + " " +
                SystemOps::ShellEscape((install_dir / "ircord-server").string()),
            "Installing ircord-server binary failed",
            callback,
            &command_error)) {
        summary.success = false;
        summary.headline = "Binary install failed";
        summary.details.push_back(command_error);
        return summary;
    }

    callback("Writing server configuration", false);
    {
        std::ofstream config_out(install_dir / "server.toml");
        config_out << BuildServerConfig(config, cert_path, key_path);
        if (!config_out) {
            summary.success = false;
            summary.headline = "Config write failed";
            summary.details.push_back("Unable to write server.toml");
            return summary;
        }
    }

    callback("Writing systemd service", false);
    {
        std::ofstream unit_out("/etc/systemd/system/ircord-server.service");
        unit_out << BuildSystemdUnit(config);
        if (!unit_out) {
            summary.success = false;
            summary.headline = "Service write failed";
            summary.details.push_back("Unable to write /etc/systemd/system/ircord-server.service");
            return summary;
        }
    }

    if (config.tls_mode == TlsMode::LetsEncrypt) {
        callback("Installing Let's Encrypt renewal hook", false);
        std::filesystem::create_directories("/etc/letsencrypt/renewal-hooks/post");
        std::ofstream hook("/etc/letsencrypt/renewal-hooks/post/ircord.sh");
        hook << "#!/bin/bash\n";
        hook << "systemctl reload-or-restart ircord-server\n";
        hook.close();
        if (!RunOrCapture(
                "chmod +x /etc/letsencrypt/renewal-hooks/post/ircord.sh",
                "Failed to mark renewal hook executable",
                callback,
                &command_error)) {
            summary.success = false;
            summary.headline = "Renewal hook setup failed";
            summary.details.push_back(command_error);
            return summary;
        }
    }

    if (config.manage_firewall) {
        callback("Configuring firewall", false);
        if (!SystemOps::CommandExists("ufw") && !config.install_ufw_if_missing) {
            summary.manual_firewall_ports.push_back("22/tcp");
            summary.manual_firewall_ports.push_back(config.port_text + "/tcp");
            if (config.tls_mode == TlsMode::LetsEncrypt) {
                summary.manual_firewall_ports.push_back("80/tcp");
            }
        } else {
            if (!RunOrCapture("ufw allow 22/tcp", "Failed to open SSH in ufw", callback, &command_error) ||
                !RunOrCapture("ufw allow " + config.port_text + "/tcp",
                              "Failed to open IRCord port in ufw",
                              callback,
                              &command_error)) {
                summary.success = false;
                summary.headline = "Firewall setup failed";
                summary.details.push_back(command_error);
                return summary;
            }
            if (config.tls_mode == TlsMode::LetsEncrypt &&
                !RunOrCapture("ufw allow 80/tcp",
                              "Failed to open port 80 in ufw",
                              callback,
                              &command_error)) {
                summary.success = false;
                summary.headline = "Firewall setup failed";
                summary.details.push_back(command_error);
                return summary;
            }
            if (!RunOrCapture("ufw --force enable", "Failed to enable ufw", callback, &command_error)) {
                summary.success = false;
                summary.headline = "Firewall setup failed";
                summary.details.push_back(command_error);
                return summary;
            }
        }
    }

    callback("Enabling systemd service", false);
    if (!RunOrCapture("systemctl daemon-reload", "systemctl daemon-reload failed", callback, &command_error) ||
        !RunOrCapture("systemctl enable ircord-server", "systemctl enable failed", callback, &command_error)) {
        summary.success = false;
        summary.headline = "Service enable failed";
        summary.details.push_back(command_error);
        return summary;
    }

    if (config.start_after_install) {
        callback("Starting IRCord", false);
        if (!RunOrCapture("systemctl start ircord-server", "systemctl start failed", callback, &command_error) ||
            !RunOrCapture("systemctl is-active --quiet ircord-server",
                          "ircord-server did not remain active after start",
                          callback,
                          &command_error) ||
            !RunOrCapture("ss -tln | grep -q :" + config.port_text,
                          "Configured IRCord port is not listening",
                          callback,
                          &command_error)) {
            summary.success = false;
            summary.headline = "Service verification failed";
            summary.details.push_back(command_error);
            summary.details.push_back("Check logs with: journalctl -u ircord-server -n 50");
            return summary;
        }
    }

    summary.success = true;
    summary.headline = "IRCord installed successfully";
    summary.details.push_back("Server port: " + config.port_text);
    summary.details.push_back("Config: " + summary.config_path);
    summary.details.push_back("Logs: journalctl -u ircord-server -f");
    if (!summary.manual_firewall_ports.empty()) {
        summary.details.push_back("Manual firewall ports: " + Join(summary.manual_firewall_ports, ", "));
    }
    return summary;
}

}  // namespace ircord::installer
